
/**
 * Criado por: Felipe M. Santos
 */

//Anuncio
export const SALVAR_ANUNCIO = 'SALVAR_ANUNCIO'
export const ATUALIZAR_ANUNCIO = 'ATUALIZAR_ANUNCIO'
export const LISTAR_TODOS_ANUNCIOS = 'LISTAR_TODOS_ANUNCIOS'

//Perguntas
export const GET_PERGUNTAS = 'GET_PERGUNTAS'
export const GET_QTDE_PERGUNTAS = 'GET_QTDE_PERGUNTAS'

//Cliente
export const LISTAR_TODOS_CLIENTES = 'LISTAR_TODOS_CLIENTES'
export const CARREGAR_DADOS_COMPRAS_POR_CLIENTE = 'CARREGAR_DADOS_COMPRAS_POR_CLIENTE'

//Venda
export const GET_VENDAS_PENDENTES = 'GET_VENDAS_PENDENTES'
export const GET_VENDAS_CONCLUIDAS = 'GET_VENDAS_CONCLUIDAS'
export const GET_VENDAS_EM_TRANSITO = 'GET_VENDAS_EM_TRANSITO'
export const GET_VENDAS_A_ENVIAR = 'GET_VENDAS_A_ENVIAR'
export const GET_TOTAL_VENDAS = 'GET_TOTAL_VENDAS'
export const GET_TOTAL_VENDAS_EM_TRANSITO = 'GET_TOTAL_VENDAS_EM_TRANSITO'
export const GET_TOTAL_VENDAS_A_ENVIAR = 'GET_TOTAL_VENDAS_A_ENVIAR'
export const GET_TOTAL_VENDAS_PENDENTES = 'GET_TOTAL_VENDAS_PENDENTES'
export const GET_DADOS_RASTREAMENTO = 'GET_DADOS_RASTREAMENTO'

//Dashboard
export const OBTER_VENDAS_PENDENTE = 'OBTER_VENDAS_PENDENTE'
export const OBTER_TOTAL_VENDAS_NO_MES = 'OBTER_TOTAL_VENDAS_NO_MES'
export const OBTER_SALDO_TOTAL = 'OBTER_SALDO_TOTAL'
export const OBTER_STATUS_ANUNCIOS = 'OBTER_STATUS_ANUNCIOS'

//Loading
export const CARREGANDO_AGUARDE = 'Carregando, aguarde...'

//OPEN_DRAWER_MENU
export const OPEN_DRAWER_MENU = 'OPEN_DRAWER_MENU'

//Domain production
//export const DOMAIN = ''

export const DOMAIN = 'http://localhost:5000'


